### ISSUE TITLE
biom 2.x examples on website are not valid examples

### ISSUE THREAD

**Issue by rec3141** [biocore/biom-format#751]
In the docs there is a section called "Example biom files" that says "Below are examples of minimal and rich biom files." [http://biom-format.org/documentation/format_versions/biom-2.0.html]

But the included text is not a valid HDF5 biom file. This is confusing for people unfamiliar with HDF5/biom like me who don't already know that it is a binary file format. In fact I couldn't find anywhere on the biom-format.org website where it says that biom 2.x is a binary format, or what kind of compression is used to generate the files. The generic links to https://www.hdfgroup.org/ are not that helpful.

It would be useful to include a direct link to the github repo housing actual example biom files. Thanks

**Comment by wasade** [comment]
Thank you for the comment. In retrospect, that page is a little confusing. The output displayed there is valid HDF5 DDL, but you are correct that it is not the actual files themselves. And I agree that a link to the examples included in the repo would be a light change to improve clarity. 

I cannot issue these changes today unfortunately but I'll put them in the queue. Do you by chance have bandwidth to issue a PR?

**Comment by rec3141** [comment]
I'm not very good at github but I think this is right
#753 #752

**Comment by wasade** [comment]
Thank you! I'll look shortly

On May 24, 2017 19:14, "rec3141" <notifications@github.com> wrote:

I'm not very good at github but I think this is right
#753 <https://github.com/biocore/biom-format/pull/753> #752
<https://github.com/biocore/biom-format/pull/752>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/biocore/biom-format/issues/751#issuecomment-303903378>,
or mute the thread

**Comment by wasade** [comment]
Thank you, @rec3141! As a heads up, it would have also been okay to do the changes within a single PR. And no worries re: github, there is definitely a learning curve and every project has different norms which might not be fully articulated.

**Comment by wasade** [comment]
These PRs were merged, closing this issue.
