### ISSUE TITLE
Add sampling with replacement to Table.subsample

### ISSUE THREAD

**Issue by wasade** [biocore/biom-format#774]
This could likely adapt the strategy used in [scikit-bio](https://github.com/biocore/scikit-bio/blob/107fc8fba3df69ceea6dd3ef357212eecc1f9be3/skbio/stats/_subsample.py#L241) and is important for instances where the sum of a vector is massive. 

Cc @mortonjt (couldn't assign for some reason)

**Comment by mortonjt** [comment]
Quick question on reproducibility

Looking at the tests for [`Table.subsample`]https://github.com/biocore/biom-format/blob/master/tests/test_table.py#L2619)  I don't see any uses of numpy random seeds.  And I'm having trouble making consistent unittests when using `Table.subsample`.

@wasade , any thoughts on setting random seeds?

**Comment by wasade** [comment]
No strong feelings

**Comment by stevendbrown** [comment]
Do either of you have a pre-PR branch for this that I could try to pick up and carry forward?

**Comment by wasade** [comment]
@stevendbrown, thank you for the inquiry! If you have bandwidth, we'd love a PR. The change should be relatively small, as it should just require a branch and call to `np.random.multinomial` as done [here](https://github.com/biocore/scikit-bio/blob/107fc8fba3df69ceea6dd3ef357212eecc1f9be3/skbio/stats/_subsample.py#L240-L241). I don't think this needs to be done within the Cython code. This would also be a pleasant feature expansion for [`q2-feature-table`](https://github.com/qiime2/q2-feature-table/blob/master/q2_feature_table/_subsample.py) and I would commit to making sure your contribution is available in the next release of QIIME 2.

**Comment by stevendbrown** [comment]
@wasade OK, I made a basic implementation but I did it in the Cython code since that logic is already worked out, and doesn't require using dense data. I'm checking my work now to make sure I didn't bungle something non-obviously, but on the surface it looks pretty clean. Are there reasons I shouldn't do this and should do it instead using pure Python (e.g. maybe writing tests is harder)?

**Comment by mortonjt** [comment]
Note that the numpy implementation of multinomial is already written in C -- not entirely sure how much faster it will be in a cython implementation ...

**Comment by stevendbrown** [comment]
@mortonjt Agreed. For me it's less about speed and more about piggyback on the existing Cython code to manipulate sparse data as input to `multinomial`. It's the "record-keeping" code around the subsampling of which I'm trying to take advantage, rather than recapitulating the existing Cython gymnastics (e.g. looping over `idxptr`) for handling the sparse matrix data a level up in `table.py`. I'll get this into a PR and maybe we can discuss options there?

**Comment by mortonjt** [comment]
👍 Look forward to seeing your PR!

**Comment by stevendbrown** [comment]
Presumably this can be closed?

**Comment by wasade** [comment]
Yes, thanks. Used to the issues getting closed automagically :)
