### ISSUE TITLE
Duplicate observation IDs error even no duplication was found

### ISSUE THREAD

**Issue by mortonjt** [biocore/biom-format#976]
Issue was first reported here https://github.com/scikit-bio/scikit-bio/issues/2121

@quliping let's continue the discussion here for future reference

**Comment by wasade** [comment]
Odd. Could be an evaluation order or in the errcheck. What happens if the table is loaded directly into biom without using pandas?

**Comment by quliping** [comment]
> Odd. Could be an evaluation order or in the errcheck. What happens if the table is loaded directly into biom without using pandas?

Sory for the late reply. I tried `Table.from_tsv()`, and it worked. I'm not sure if I should use this command, but the table was loaded into biom successfully. 

And I think I found the reason... I tried my orignal script, `asv_table = Table(df.T.values, observation_ids, sample_ids)` worked but  `asv_table = Table(df.values, observation_ids, sample_ids)` got the 'Duplicate observation IDs' error. It seems like I made a mistake for the row and column contents. Each column should be a sample and each row should be a species, right? I got it wrong before (I inverted my table). I think the error message is confusing and perhaps should change to something like 'The number of columns is different from the number of given sample ids, please check if there is a mistake in the placement of samples and observations in given table.' Because there are indeed no duplicate ids...

By the way, the description for the input data of 'skbio.diversity.alpha_diversity' is 'Vector or matrix containing count/abundance data. If a matrix, each row should contain counts of taxa in a given sample.' It may be confusing, it sound something like 'each row is the content of a sample (and each column is a species...)', so I used to wonder why the input data was different from the biom format then put my sample ids in teh first column... May be it should be changed to ' If a matrix, each row contains the counts of a taxon in given samples, and each column contains the counts of all taxa in a sample.'

![image](https://github.com/user-attachments/assets/61222655-351c-4b2f-944c-22f21b4b7529)

**Comment by wasade** [comment]
A traditional feature table, dating from QIIME 1 days, has rows as observations and that is modeled in BIOM. That's correct though that the error message is wrong, as it seems this should trigger a shape or related error, and that would be valuable to fix. Thank you for reporting!

**Comment by wasade** [comment]
I believe this is closed, please reopen if incorrect
